dict_mercado = {
    'Epa (Centro)':	{'id': 1, 'regiao': 'Centro'},
    'São José (Centro)': {'id': 2, 'regiao': 'Centro'},
    'OK Hipermercado (Barro Vermelho)': {'id': 6, 'regiao': 'Santo Antônio'},
    'MultiMarket (Super Lar) (Santo Antônio)': {'id': 7, 'regiao': 'Santo Antônio'},
    'Supermercados Fieni (Lourdes)': {'id': 8, 'regiao': 'Bento Ferreira'},
    'Epa (Ilha Monte Belo)': {'id': 9, 'regiao': 'Bento Ferreira'},
    'Zaneti (Fradinhos)': {'id': 10, 'regiao': 'Bento Ferreira'},
    'Schowambach (Santa Marta)': {'id': 11, 'regiao': 'Maruípe'},
    'Extrabom (Itararé)': {'id': 13, 'regiao': 'Maruípe'},
    'Carone (Santa Lúcia)': {'id': 16, 'regiao': 'Praia do Canto'},
    'São José (Praia do Canto)': {'id': 17, 'regiao': 'Praia do Canto'},
    'Epa (Santa Lúcia)': {'id': 18, 'regiao': 'Praia do Canto'},
    'Walmart (Santa Luiza)': {'id': 19, 'regiao': 'Praia do Canto'},
    'Perim (Mata da Praia)': {'id': 20, 'regiao': 'Continental'},
    'Epa (Jardim da Penha)': {'id': 21, 'regiao': 'Continental'},
    'Carone (Jardim da Penha)': {'id': 22, 'regiao': 'Continental'},
    'Extrabom (Goiabeiras)': {'id': 23, 'regiao': 'Continental'},
    'Nossa Rede Supermercados (Resistência)': {'id': 24, 'regiao': 'São Pedro'},
    'MultiShow (Redenção)': {'id': 28, 'regiao': 'São Pedro'},
    'Carone (Jardim Camburi)': {'id': 29, 'regiao': 'Camburi'},
    'Epa (Jardim Camburi)': {'id': 30, 'regiao': 'Camburi'}
}

dict_produto = {
    'Ovos de Galinha (Dúzia) - Preço 1': {'descricao': 'Ovo de Galinha', 'preco': 'preco_1', 'peso': 1, 'peso_obs': 1},
    'Ovos de Galinha (Dúzia) - Preço 2': {'descricao': 'Ovo de Galinha', 'preco': 'preco_2', 'peso': 1, 'peso_obs': 1},
    'Ovos de Galinha (Dúzia) - Preço 3': {'descricao': 'Ovo de Galinha', 'preco': 'preco_3', 'peso': 1, 'peso_obs': 1},
    'Água Mineral (1l) - Preço 1': {'descricao': 'Água Mineral', 'preco': 'preco_1', 'peso': 1, 'peso_obs': 1},
    'Água Mineral (1l) - Preço 2': {'descricao': 'Água Mineral', 'preco': 'preco_2', 'peso': 1, 'peso_obs': 1},
    'Água Mineral (1l) - Preço 3': {'descricao': 'Água Mineral', 'preco': 'preco_3', 'peso': 1, 'peso_obs': 1},
    'Refrigerante (2l) - Preço 1': {'descricao': 'Refrigerante', 'preco': 'preco_1', 'peso': 2, 'peso_obs': 2},
    'Refrigerante (2l) - Preço 2': {'descricao': 'Refrigerante', 'preco': 'preco_2', 'peso': 2, 'peso_obs': 2},
    'Refrigerante (2l) - Preço 3': {'descricao': 'Refrigerante', 'preco': 'preco_3', 'peso': 2, 'peso_obs': 2},
    'Refrigerante Light (2l) - Preço 1': {'descricao': 'Refrigerante Light', 'preco': 'preco_1', 'peso': 2,
                                          'peso_obs': 2},
    'Refrigerante Light (2l) - Preço 2': {'descricao': 'Refrigerante Light', 'preco': 'preco_2', 'peso': 2,
                                          'peso_obs': 2},
    'Refrigerante Light (2l) - Preço 3': {'descricao': 'Refrigerante Light', 'preco': 'preco_3', 'peso': 2,
                                          'peso_obs': 2},
    'Vinho Tinto (750ml) - Preço 1': {'descricao': 'Vinho', 'preco': 'preco_1', 'peso': 0.375, 'peso_obs': 0.75},
    'Vinho Tinto (750ml) - Preço 2': {'descricao': 'Vinho', 'preco': 'preco_2', 'peso': 0.375, 'peso_obs': 0.75},
    'Vinho Tinto (750ml) - Preço 3': {'descricao': 'Vinho', 'preco': 'preco_3', 'peso': 0.375, 'peso_obs': 0.75},
    'Óleo de Soja (900ml) - Preço 1': {'descricao': 'Óleo de Soja', 'preco': 'preco_1', 'peso': 1, 'peso_obs': 1},
    'Óleo de Soja (900ml) - Preço 2': {'descricao': 'Óleo de Soja', 'preco': 'preco_2', 'peso': 1, 'peso_obs': 1},
    'Óleo de Soja (900ml) - Preço 3': {'descricao': 'Óleo de Soja', 'preco': 'preco_3', 'peso': 1, 'peso_obs': 1},
    'Milho Verde Lata (220g) - Preço 1': {'descricao': 'Milho Verde Conserva', 'preco': 'preco_1', 'peso': 0.2,
                                              'peso_obs': 0.2},
    'Milho Verde Lata (220g) - Preço 2': {'descricao': 'Milho Verde Conserva', 'preco': 'preco_2', 'peso': 0.2,
                                              'peso_obs': 0.2},
    'Milho Verde Lata (220g) - Preço 3': {'descricao': 'Milho Verde Conserva', 'preco': 'preco_3', 'peso': 0.2,
                                              'peso_obs': 0.2},
    'Cerveja Nacional (350ml) - Preço 1': {'descricao': 'Cerveja Nacional', 'preco': 'preco_1', 'peso': 0.35,
                                            'peso_obs': 0.35},
    'Cerveja Nacional (350ml) - Preço 2': {'descricao': 'Cerveja Nacional', 'preco': 'preco_2', 'peso': 0.35,
                                            'peso_obs': 0.35},
    'Cerveja Nacional (350ml) - Preço 3': {'descricao': 'Cerveja Nacional', 'preco': 'preco_3', 'peso': 0.35,
                                            'peso_obs': 0.35},
    'Pêssego em Calda (450g) - Preço 1': {'descricao': 'Lata de Pêssego ', 'preco': 'preco_1', 'peso': 1,
                                          'peso_obs': 0.450},
    'Pêssego em Calda (450g) - Preço 2': {'descricao': 'Lata de Pêssego ', 'preco': 'preco_2', 'peso': 1,
                                          'peso_obs': 0.450},
    'Pêssego em Calda (450g) - Preço 3': {'descricao': 'Lata de Pêssego ', 'preco': 'preco_3', 'peso': 1,
                                          'peso_obs': 0.450},
    'Farinha de Trigo (1kg) - Preço 1': {'descricao': 'Farinha de Trigo', 'preco': 'preco_1', 'peso': 1, 'peso_obs': 1},
    'Farinha de Trigo (1kg) - Preço 2': {'descricao': 'Farinha de Trigo', 'preco': 'preco_2', 'peso': 1, 'peso_obs': 1},
    'Farinha de Trigo (1kg) - Preço 3': {'descricao': 'Farinha de Trigo', 'preco': 'preco_3', 'peso': 1, 'peso_obs': 1},
    'Farinha de Trigo Integral (1kg) - Preço 1': {'descricao': 'Farinha de Trigo Integral', 'preco': 'preco_1', 'peso': 1,
                                          'peso_obs': 1},
    'Farinha de Trigo Integral (1kg) - Preço 2': {'descricao': 'Farinha de Trigo Integral', 'preco': 'preco_2', 'peso': 1,
                                          'peso_obs': 1},
    'Farinha de Trigo Integral (1kg) - Preço 3': {'descricao': 'Farinha de Trigo Integral', 'preco': 'preco_3', 'peso': 1,
                                          'peso_obs': 1},
    'Biscoito Água e Sal (1 pacote) - Preço 1': {'descricao': 'Biscoito Água e Sal', 'preco': 'preco_1', 'peso': 0.2,
                                                 'peso_obs': 0.2},
    'Biscoito Água e Sal (1 pacote) - Preço 2': {'descricao': 'Biscoito Água e Sal', 'preco': 'preco_2', 'peso': 0.2,
                                                 'peso_obs': 0.2},
    'Biscoito Água e Sal (1 pacote) - Preço 3': {'descricao': 'Biscoito Água e Sal', 'preco': 'preco_3', 'peso': 0.2,
                                                 'peso_obs': 0.2},
    'Açúcar Cristal (5kg) - Preço 1': {'descricao': 'Açúcar', 'preco': 'preco_1', 'peso': 2, 'peso_obs': 5},
    'Açúcar Cristal (5kg) - Preço 2': {'descricao': 'Açúcar', 'preco': 'preco_2', 'peso': 2, 'peso_obs': 5},
    'Açúcar Cristal (5kg) - Preço 3': {'descricao': 'Açúcar', 'preco': 'preco_3', 'peso': 2, 'peso_obs': 5},
    'Macarrão Instantâneo (1 pacote) - Preço 1': {'descricao': 'Macarrão Instântaneo', 'preco': 'preco_1', 'peso': 1,
                                                  'peso_obs': 1},
    'Macarrão Instantâneo (1 pacote) - Preço 2': {'descricao': 'Macarrão Instântaneo', 'preco': 'preco_2', 'peso': 1,
                                                  'peso_obs': 1},
    'Macarrão Instantâneo (1 pacote) - Preço 3': {'descricao': 'Macarrão Instântaneo', 'preco': 'preco_3', 'peso': 1,
                                                  'peso_obs': 1},
    'Margarina (250g) - Preço 1': {'descricao': 'Margarina', 'preco': 'preco_1', 'peso': 0.25, 'peso_obs': 0.25},
    'Margarina (250g) - Preço 2': {'descricao': 'Margarina', 'preco': 'preco_2', 'peso': 0.25, 'peso_obs': 0.25},
    'Margarina (250g) - Preço 3': {'descricao': 'Margarina', 'preco': 'preco_3', 'peso': 0.25, 'peso_obs': 0.25},
    'Margarina Light (250g) - Preço 1': {'descricao': 'Margarina Light', 'preco': 'preco_1', 'peso': 0.25,
                                         'peso_obs': 0.25},
    'Margarina Light (250g) - Preço 2': {'descricao': 'Margarina Light', 'preco': 'preco_2', 'peso': 0.25,
                                         'peso_obs': 0.25},
    'Margarina Light (250g) - Preço 3': {'descricao': 'Margarina Light', 'preco': 'preco_3', 'peso': 0.25,
                                         'peso_obs': 0.25},
    'Café Solúvel em Pó (50g) - Preço 1': {'descricao': 'Café Solúvel', 'preco': 'preco_1', 'peso': 0.05,
                                            'peso_obs': 0.05},
    'Café Solúvel em Pó (50g) - Preço 2': {'descricao': 'Café Solúvel', 'preco': 'preco_2', 'peso': 0.05,
                                            'peso_obs': 0.05},
    'Café Solúvel em Pó (50g) - Preço 3': {'descricao': 'Café Solúvel', 'preco': 'preco_3', 'peso': 0.05,
                                            'peso_obs': 0.05},
    'Adoçante (100ml) - Preço 1': {'descricao': 'Adoçante', 'preco': 'preco_1', 'peso': 0.1, 'peso_obs': 0.1},
    'Adoçante (100ml) - Preço 2': {'descricao': 'Adoçante', 'preco': 'preco_2', 'peso': 0.1, 'peso_obs': 0.1},
    'Adoçante (100ml) - Preço 3': {'descricao': 'Adoçante', 'preco': 'preco_3', 'peso': 0.1, 'peso_obs': 0.1},
    'Banana (1kg) - Preço 1': {'descricao': 'Banana', 'preco': 'preco_1', 'peso': 1, 'peso_obs': 1},
    'Banana (1kg) - Preço 2': {'descricao': 'Banana', 'preco': 'preco_2', 'peso': 1, 'peso_obs': 1},
    'Banana (1kg) - Preço 3': {'descricao': 'Banana', 'preco': 'preco_3', 'peso': 1, 'peso_obs': 1},
    'Soja em Grãos (500g) - Preço 1': {'descricao': 'Soja em Grão', 'preco': 'preco_1', 'peso': 1, 'peso_obs': 0.5},
    'Soja em Grãos (500g) - Preço 2': {'descricao': 'Soja em Grão', 'preco': 'preco_2', 'peso': 1, 'peso_obs': 0.5},
    'Soja em Grãos (500g) - Preço 3': {'descricao': 'Soja em Grão', 'preco': 'preco_3', 'peso': 1, 'peso_obs': 0.5},
    'Feijão Preto (1kg) - Preço 1': {'descricao': 'Feijão Preto', 'preco': 'preco_1', 'peso': 1, 'peso_obs': 1},
    'Feijão Preto (1kg) - Preço 2': {'descricao': 'Feijão Preto', 'preco': 'preco_2', 'peso': 1, 'peso_obs': 1},
    'Feijão Preto (1kg) - Preço 3': {'descricao': 'Feijão Preto', 'preco': 'preco_3', 'peso': 1, 'peso_obs': 1},
    'Grão de Bico (500g) - Preço 1': {'descricao': 'Grão de Bico', 'preco': 'preco_1', 'peso': 1, 'peso_obs': 0.5},
    'Grão de Bico (500g) - Preço 2': {'descricao': 'Grão de Bico', 'preco': 'preco_2', 'peso': 1, 'peso_obs': 0.5},
    'Grão de Bico (500g) - Preço 3': {'descricao': 'Grão de Bico', 'preco': 'preco_3', 'peso': 1, 'peso_obs': 0.5},
    'Laranja (1kg) - Preço 1': {'descricao': 'Laranja', 'preco': 'preco_1', 'peso': 1, 'peso_obs': 1},
    'Laranja (1kg) - Preço 2': {'descricao': 'Laranja', 'preco': 'preco_2', 'peso': 1, 'peso_obs': 1},
    'Laranja (1kg) - Preço 3': {'descricao': 'Laranja', 'preco': 'preco_3', 'peso': 1, 'peso_obs': 1},
    'Pão Integral (1 pacote) - Preço 1': {'descricao': 'Pão Integral', 'preco': 'preco_1', 'peso': 0.4, 'peso_obs': 0.4},
    'Pão Integral (1 pacote) - Preço 2': {'descricao': 'Pão Integral', 'preco': 'preco_2', 'peso': 0.4, 'peso_obs': 0.4},
    'Pão Integral (1 pacote) - Preço 3': {'descricao': 'Pão Integral', 'preco': 'preco_3', 'peso': 0.4, 'peso_obs': 0.4},
    'Sardinha Enlatada (1 lata) - Preço 1': {'descricao': 'Sardinha Lata', 'preco': 'preco_1', 'peso': 0.25,
                                             'peso_obs': 1},
    'Sardinha Enlatada (1 lata) - Preço 2': {'descricao': 'Sardinha Lata', 'preco': 'preco_2', 'peso': 0.25,
                                             'peso_obs': 1},
    'Sardinha Enlatada (1 lata) - Preço 3': {'descricao': 'Sardinha Lata', 'preco': 'preco_3', 'peso': 0.25,
                                             'peso_obs': 1},
    'Suco de Uva (1l) - Preço 1': {'descricao': 'Suco de Uva', 'preco': 'preco_1', 'peso': 2, 'peso_obs': 1},
    'Suco de Uva (1l) - Preço 2': {'descricao': 'Suco de Uva', 'preco': 'preco_2', 'peso': 2, 'peso_obs': 1},
    'Suco de Uva (1l) - Preço 3': {'descricao': 'Suco de Uva', 'preco': 'preco_3', 'peso': 2, 'peso_obs': 1},
    'Spaguetti de Ovos (500g) - Preço 1': {'descricao': 'Massa de Espaguete', 'preco': 'preco_1', 'peso': 0.5,
                                           'peso_obs': 0.5},
    'Spaguetti de Ovos (500g) - Preço 2': {'descricao': 'Massa de Espaguete', 'preco': 'preco_2', 'peso': 0.5,
                                           'peso_obs': 0.5},
    'Spaguetti de Ovos (500g) - Preço 3': {'descricao': 'Massa de Espaguete', 'preco': 'preco_3', 'peso': 0.5,
                                           'peso_obs': 0.5},
    'Spaguetti de Sêmola (500g) - Preço 1': {'descricao': 'Massa de Espaguete Semola', 'preco': 'preco_1', 'peso': 0.5,
                                             'peso_obs': 0.5},
    'Spaguetti de Sêmola (500g) - Preço 2': {'descricao': 'Massa de Espaguete Semola', 'preco': 'preco_2', 'peso': 0.5,
                                             'peso_obs': 0.5},
    'Spaguetti de Sêmola (500g) - Preço 3': {'descricao': 'Massa de Espaguete Semola', 'preco': 'preco_3', 'peso': 0.5,
                                             'peso_obs': 0.5},
    'Café Torrado e Moído (250g) - Preço 1': {'descricao': 'Café Tradicional', 'preco': 'preco_1', 'peso': 0.25,
                                              'peso_obs': 0.25},
    'Café Torrado e Moído (250g) - Preço 2': {'descricao': 'Café Tradicional', 'preco': 'preco_2', 'peso': 0.25,
                                              'peso_obs': 0.25},
    'Café Torrado e Moído (250g) - Preço 3': {'descricao': 'Café Tradicional', 'preco': 'preco_3', 'peso': 0.25,
                                              'peso_obs': 0.25},
    'Presunto (1kg) - Preço 1': {'descricao': 'Presunto', 'preco': 'preco_1', 'peso': 0.25, 'peso_obs': 1},
    'Presunto (1kg) - Preço 2': {'descricao': 'Presunto', 'preco': 'preco_2', 'peso': 0.25, 'peso_obs': 1},
    'Presunto (1kg) - Preço 3': {'descricao': 'Presunto', 'preco': 'preco_3', 'peso': 0.25, 'peso_obs': 1},
    'Queijo Minas Frescal (1kg) - Preço 1': {'descricao': 'Queijo Minas', 'preco': 'preco_1', 'peso': 0.25,
                                             'peso_obs': 1},
    'Queijo Minas Frescal (1kg) - Preço 2': {'descricao': 'Queijo Minas', 'preco': 'preco_2', 'peso': 0.25,
                                             'peso_obs': 1},
    'Queijo Minas Frescal (1kg) - Preço 3': {'descricao': 'Queijo Minas', 'preco': 'preco_3', 'peso': 0.25,
                                             'peso_obs': 1},
    'Queijo Prato (1kg) - Preço 1': {'descricao': 'Queijo Prato', 'preco': 'preco_1', 'peso': 0.25, 'peso_obs': 1},
    'Queijo Prato (1kg) - Preço 2': {'descricao': 'Queijo Prato', 'preco': 'preco_2', 'peso': 0.25, 'peso_obs': 1},
    'Queijo Prato (1kg) - Preço 3': {'descricao': 'Queijo Prato', 'preco': 'preco_3', 'peso': 0.25, 'peso_obs': 1},
    'Sal Refinado (1kg) - Preço 1': {'descricao': 'Sal Refinado', 'preco': 'preco_1', 'peso': 0.25, 'peso_obs': 1},
    'Sal Refinado (1kg) - Preço 2': {'descricao': 'Sal Refinado', 'preco': 'preco_2', 'peso': 0.25, 'peso_obs': 1},
    'Sal Refinado (1kg) - Preço 3': {'descricao': 'Sal Refinado', 'preco': 'preco_3', 'peso': 0.25, 'peso_obs': 1},
    'Proteína de Soja Granulada (400g) - Preço 1': {'descricao': 'Proteína de Soja', 'preco': 'preco_1', 'peso': 2,
                                                    'peso_obs': 1},
    'Proteína de Soja Granulada (400g) - Preço 2': {'descricao': 'Proteína de Soja', 'preco': 'preco_2', 'peso': 2,
                                                    'peso_obs': 1},
    'Proteína de Soja Granulada (400g) - Preço 3': {'descricao': 'Proteína de Soja', 'preco': 'preco_3', 'peso': 2,
                                                    'peso_obs': 1},
    'Arroz Branco (5kg) - Preço 1': {'descricao': 'Arroz Branco', 'preco': 'preco_1', 'peso': 2, 'peso_obs': 5},
    'Arroz Branco (5kg) - Preço 2': {'descricao': 'Arroz Branco', 'preco': 'preco_2', 'peso': 2, 'peso_obs': 5},
    'Arroz Branco (5kg) - Preço 3': {'descricao': 'Arroz Branco', 'preco': 'preco_3', 'peso': 2, 'peso_obs': 5},
    'Arroz Integral (1kg) - Preço 1': {'descricao': 'Arroz Integral', 'preco': 'preco_1', 'peso': 2, 'peso_obs': 1},
    'Arroz Integral (1kg) - Preço 2': {'descricao': 'Arroz Integral', 'preco': 'preco_2', 'peso': 2, 'peso_obs': 1},
    'Arroz Integral (1kg) - Preço 3': {'descricao': 'Arroz Integral', 'preco': 'preco_3', 'peso': 2, 'peso_obs': 1},
    'Frango Congelado (1kg) - Preço 1': {'descricao': 'Frango Inteiro', 'preco': 'preco_1', 'peso': 2, 'peso_obs': 1},
    'Frango Congelado (1kg) - Preço 2': {'descricao': 'Frango Inteiro', 'preco': 'preco_2', 'peso': 2, 'peso_obs': 1},
    'Frango Congelado (1kg) - Preço 3': {'descricao': 'Frango Inteiro', 'preco': 'preco_3', 'peso': 2, 'peso_obs': 1},
    'Salmão Congelado (1kg) - Preço 1': {'descricao': 'Salmão Congelado', 'preco': 'preco_1', 'peso': 0.4, 'peso_obs': 1},
    'Salmão Congelado (1kg) - Preço 2': {'descricao': 'Salmão Congelado', 'preco': 'preco_2', 'peso': 0.4, 'peso_obs': 1},
    'Salmão Congelado (1kg) - Preço 3': {'descricao': 'Salmão Congelado', 'preco': 'preco_3', 'peso': 0.4, 'peso_obs': 1},
    'Leite de Soja (1l) - Preço 1': {'descricao': 'Leite de Soja', 'preco': 'preco_1', 'peso': 4, 'peso_obs': 1},
    'Leite de Soja (1l) - Preço 2': {'descricao': 'Leite de Soja', 'preco': 'preco_2', 'peso': 4, 'peso_obs': 1},
    'Leite de Soja (1l) - Preço 3': {'descricao': 'Leite de Soja', 'preco': 'preco_3', 'peso': 4, 'peso_obs': 1},
    'Leite UHT (1l) - Preço 1': {'descricao': 'Leite Desnatado', 'preco': 'preco_1', 'peso': 4, 'peso_obs': 1},
    'Leite UHT (1l) - Preço 2': {'descricao': 'Leite Desnatado', 'preco': 'preco_2', 'peso': 4, 'peso_obs': 1},
    'Leite UHT (1l) - Preço 3': {'descricao': 'Leite Desnatado', 'preco': 'preco_3', 'peso': 4, 'peso_obs': 1},
    'Leite UHT Desnatado (1l) - Preço 1': {'descricao': 'Leite Integral', 'preco': 'preco_1', 'peso': 4, 'peso_obs': 1},
    'Leite UHT Desnatado (1l) - Preço 2': {'descricao': 'Leite Integral', 'preco': 'preco_2', 'peso': 4, 'peso_obs': 1},
    'Leite UHT Desnatado (1l) - Preço 3': {'descricao': 'Leite Integral', 'preco': 'preco_3', 'peso': 4, 'peso_obs': 1},
    'Carne Bovina (1kg) - Acém': {'descricao': 'Carne de Segunda', 'preco': 'preco_1', 'peso': 1, 'peso_obs': 1},
    'Carne Bovina (1kg) - Músculo': {'descricao': 'Carne de Segunda', 'preco': 'preco_2', 'peso': 1, 'peso_obs': 1},
    'Carne Bovina (1kg) - Pá': {'descricao': 'Carne de Segunda', 'preco': 'preco_3', 'peso': 1, 'peso_obs': 1},
    'Carne Bovina (1kg) - Alcatra': {'descricao': 'Carne de Primeira', 'preco': 'preco_1', 'peso': 1, 'peso_obs': 1},
    'Carne Bovina (1kg) - Contra-Filé': {'descricao': 'Carne de Primeira', 'preco': 'preco_2', 'peso': 1,
                                         'peso_obs': 1},
    'Carne Bovina (1kg) - Chã de Dentro': {'descricao': 'Carne de Primeira', 'preco': 'preco_3', 'peso': 1,
                                           'peso_obs': 1},
    'Batata inglesa (1kg)': {'descricao': 'Batata Inglesa', 'preco': 'preco_1', 'peso': 1, 'peso_obs': 1},
    'Inhame (1kg)': {'descricao': 'Inhame', 'preco': 'preco_1', 'peso': 1, 'peso_obs': 1},
    'Pão Francês (1kg)': {'descricao': 'Pão Francês', 'preco': 'preco_1', 'peso': 1, 'peso_obs': 1},
    'Ameixa (1kg)': {'descricao': 'Ameixa', 'preco': 'preco_1', 'peso': 0.5, 'peso_obs': 1},
    'Cebola (1kg)': {'descricao': 'Cebola', 'preco': 'preco_1', 'peso': 0.5, 'peso_obs': 1},
    'Tomate (1kg)': {'descricao': 'Tomate', 'preco': 'preco_1', 'peso': 0.5, 'peso_obs': 1},
    'Maçã (1kg)': {'descricao': 'Maçã', 'preco': 'preco_1', 'peso': 0.25, 'peso_obs': 1},
    'Maçã Argentina (1kg)': {'descricao': 'Maçã Argentina', 'preco': 'preco_1', 'peso': 0.25, 'peso_obs': 1},
    'Alface (unidade)': {'descricao': 'Alface', 'preco': 'preco_1', 'peso': 1, 'peso_obs': 1},
    'Peito de Peru Defumado Light (1kg) - Preço 1': {'descricao': 'Peito de Peru Light', 'preco': 'preco_1', 'peso': 0.25,
                                                     'peso_obs': 1},
    'Peito de Peru Defumado Light (1kg) - Preço 2': {'descricao': 'Peito de Peru Light', 'preco': 'preco_2', 'peso': 0.25,
                                                     'peso_obs': 1},
    'Peito de Peru Defumado Light (1kg) - Preço 3': {'descricao': 'Peito de Peru Light', 'preco': 'preco_3', 'peso': 0.25,
                                                     'peso_obs': 1}
}

dict_cerveja = {
    'Cerveja Premium (1 garrafa) - Preço 1': {'descricao': 'Cerveja Importada', 'preco': 'preco_1'},
    'Cerveja Premium (1 garrafa) - Preço 2': {'descricao': 'Cerveja Importada', 'preco': 'preco_2'},
    'Cerveja Premium (1 garrafa) - Preço 3': {'descricao': 'Cerveja Importada', 'preco': 'preco_3'}
}

dict_restante = {
    'Cereal Matinal (1 caixa) - Preço 1': {'descricao': 'Cereal Matinal', 'preco': 'preco_1', 'preco_ajustado': ''},
    'Cereal Matinal (1 caixa) - Preço 2': {'descricao': 'Cereal Matinal', 'preco': 'preco_2', 'preco_ajustado': ''},
    'Cereal Matinal (1 caixa) - Preço 3': {'descricao': 'Cereal Matinal', 'preco': 'preco_3', 'preco_ajustado': ''},
    'Biscoito Recheado (1 pacote) - Preço 1': {'descricao': 'Biscoito Doce', 'preco': 'preco_1', 'preco_ajustado': ''},
    'Biscoito Recheado (1 pacote) - Preço 2': {'descricao': 'Biscoito Doce', 'preco': 'preco_2', 'preco_ajustado': ''},
    'Biscoito Recheado (1 pacote) - Preço 3': {'descricao': 'Biscoito Doce', 'preco': 'preco_3', 'preco_ajustado': ''},
    'Biscoito Salgado - Preço 1': {'descricao': 'Biscoito Salgado', 'preco': 'preco_1', 'preco_ajustado': ''},
    'Biscoito Salgado - Preço 2': {'descricao': 'Biscoito Salgado', 'preco': 'preco_2', 'preco_ajustado': ''},
    'Biscoito Salgado - Preço 3': {'descricao': 'Biscoito Salgado', 'preco': 'preco_3', 'preco_ajustado': ''}
}


cesta_padrao = ['Arroz Branco', 'Milho Verde Conserva', 'Feijão Preto', 'Alface', 'Tomate', 'Cebola',
                'Batata Inglesa', 'Banana', 'Laranja', 'Maçã', 'Farinha de Trigo', 'Massa de Espaguete', 'Pão Francês',
                'Biscoito Salgado', 'Biscoito Doce', 'Carne de Segunda', 'Presunto', 'Sardinha Lata',
                'Frango Inteiro', 'Ovo de Galinha', 'Leite Integral', 'Queijo Prato', 'Açúcar', 'Sal Refinado',
                'Óleo de Soja', 'Água Mineral', 'Refrigerante', 'Cerveja Nacional', 'Macarrão Instântaneo', 'Margarina',
                'Café Solúvel']

cesta_light = ['Arroz Integral', 'Milho Verde Conserva', 'Feijão Preto', 'Alface', 'Tomate', 'Cebola',
               'Batata Inglesa',
               'Banana', 'Laranja', 'Maçã', 'Farinha de Trigo Integral', 'Massa de Espaguete', 'Pão Integral',
               'Biscoito Salgado', 'Biscoito Água e Sal', 'Carne de Segunda', 'Peito de Peru Light',
               'Sardinha Lata',
               'Frango Inteiro', 'Ovo de Galinha', 'Leite Desnatado', 'Queijo Minas', 'Adoçante', 'Sal Refinado',
               'Óleo de Soja', 'Água Mineral', 'Refrigerante Light', 'Vinho', 'Macarrão Instântaneo',
               'Margarina Light', 'Café Solúvel']

cesta_vegetariano = ['Arroz Branco', 'Milho Verde Conserva', 'Feijão Preto', 'Alface', 'Tomate', 'Cebola',
                     'Batata Inglesa', 'Banana', 'Laranja', 'Maçã', 'Farinha de Trigo', 'Massa de Espaguete Semola',
                     'Pão Francês', 'Biscoito Salgado', 'Proteína de Soja', 'Inhame', 'Grão de Bico', 'Leite de Soja',
                     'Açúcar', 'Sal Refinado', 'Óleo de Soja', 'Água Mineral', 'Refrigerante', 'Cerveja Nacional',
                     'Soja em Grão', 'Margarina', 'Café Solúvel']

cesta_top = ['Arroz Branco', 'Milho Verde Conserva', 'Feijão Preto', 'Alface', 'Tomate', 'Cebola', 'Batata Inglesa',
             'Lata de Pêssego ', 'Ameixa', 'Maçã Argentina', 'Farinha de Trigo', 'Massa de Espaguete',
             'Pão Francês',
             'Biscoito Salgado', 'Cereal Matinal', 'Carne de Primeira',
             'Salmão Congelado',
             'Frango Inteiro', 'Ovo de Galinha', 'Leite Integral', 'Queijo Prato', 'Açúcar', 'Sal Refinado',
             'Óleo de Soja', 'Água Mineral', 'Suco de Uva', 'Cerveja Premium', 'Macarrão Instântaneo',
             'Margarina', 'Café Tradicional']
